//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using ROITest.Data;

//namespace ROITest.Data.Migrations
//{
//    [DbContext(typeof(ToDoContext))]
//    [Migration("20200926112313_InitialCreate")]
//    partial class InitialCreate
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "3.1.8");

//            modelBuilder.Entity("ROITest.Models.ToDoModel", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<bool?>("Done")
//                        .HasColumnType("INTEGER");

//                    b.Property<DateTime?>("DueDate")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Title")
//                        .HasColumnType("TEXT");

//                    b.HasKey("Id");

//                    b.ToTable("ToDos");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
